import LanguageSwitcher from "@/components/language-switcher";
import NavbarHome from "@/components/nav";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Inter } from "next/font/google";

import Layout from "@/components/Navlayout";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VooTreeVeeVuu",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <Layout
    // className=" bg-gray-50"
    >
      {children}
    </Layout>
  );
}
